- name:deploying to tomcat
  hosts:web
  become:yes
  tasks:
  - name: cpoying war file to tomcat
    copy:
     src:"/var/snap/jenkins/4874/workspace/myweb99/target/myweb99.war"
     dest:"/opt/tomcat/webapps/myweb99.war"
     remote_src: no
  - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restartedq
